version: "3"
services:
    web:
        build: .
        image: trippbot
        depends_on:
            - db
    db:
        image: postgres:9
        volumes:
            - "./sql:/docker-entrypoint-initdb.d"
            - "dbdata:/var/lib/postgresql/data"
volumes:
    dbdata:
